Favicon #4
front-end-by-rimantas/41-grupe-portfolio-neuron pull request #45
Opened 2023-01-04 16:23 UTC by VladimirKarin

Issue #4  done.

2023-01-04 17:38 UTC, Zukauskas requested changes

2023-01-04 17:38 UTC, Zukauskas commented on index.html
> +</body>
čia iš esmės matau keičia visą formatavimą, bet dėl šito tai viskas gerai, po to kitą pull requestą supushinsim kur irgi keičia tai žėsim kokie konfliktai bus :D

2023-01-04 17:38 UTC, Zukauskas commented on index.html
> +    <meta name="theme-color" content="#ffffff">
trūksta link į pagrindinį favicon :D

2023-01-04 17:51 UTC, Zukauskas approved these changes
Liuks

2023-01-05 09:12 UTC, aurimas1551 approved these changes

2023-01-05 09:45 UTC, merged