About us #26
front-end-by-rimantas/41-grupe-portfolio-neuron pull request #65
Opened 2023-01-13 15:10 UTC by VladimirKarin

Responsive "About us" section

2023-01-13 15:32 UTC, Zukauskas requested changes
Šiaip nice atrodo, tiktai keletas dar dalykų susitaisymui, nors gal realiai negadina vaizdo, bet likučiai tokie :))

2023-01-13 15:32 UTC, Zukauskas commented on css/pages/home.css
> +@import '../pages/about-us.css';
component'ą geriausiai būtų prie components skilties /*components*/ prideti, abeceles tvarka :)

2023-01-13 15:32 UTC, Zukauskas commented on index.html
> +    <Section id="neuron-about" class="container">
čia man tik vaidenasi ar section iš didžiosios parašyta? :)))

2023-01-13 15:32 UTC, Zukauskas commented on index.html
> +    </Section>
ir čia :)

2023-01-13 15:32 UTC, Zukauskas commented on index.html
> +                            </i class=>
kažkokia pasiklydus class atrodo :D

2023-01-13 15:46 UTC, VladimirKarin commented on index.html
> +    </Section>
done

2023-01-14 15:28 UTC, Zukauskas approved these changes

2023-01-15 10:38 UTC, aurimas1551 approved these changes

2023-01-15 10:38 UTC, merged